In [ ]:
import tensorflow as ft
print(ft.__version__)

2.15.0


In [ ]:
sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
voc_size=10000

In [ ]:
onehot_represent=[one_hot(words,voc_size)for words in sent]
print(onehot_represent)

[[4888, 5040, 5851, 9384, 7923, 288], [5740, 5395, 5851, 372, 985, 9825], [69, 7194, 8125, 7962], [4888, 3675, 5851, 3763, 4888, 6924], [575, 767, 1439, 5851, 372, 985, 9825], [8603, 5851, 372, 985, 5677, 6773]]


In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length=10
embedded_docs=pad_sequences(onehot_represent,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4888 5040 5851 9384 7923  288]
 [   0    0    0    0 5740 5395 5851  372  985 9825]
 [   0    0    0    0    0    0   69 7194 8125 7962]
 [   0    0    0    0 4888 3675 5851 3763 4888 6924]
 [   0    0    0  575  767 1439 5851  372  985 9825]
 [   0    0    0    0 8603 5851  372  985 5677 6773]]


In [ ]:
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 10)            100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 4888, 5040, 5851, 9384, 7923,  288],
      dtype=int32)

In [ ]:
model.predict(embedded_docs[0]).reshape(-1,1)

1/1 [==============================] - 0s 49ms/step


array([[ 0.01815932],
       [ 0.02761726],
       [-0.00256782],
       [-0.0430895 ],
       [ 0.04524681],
       [ 0.04253869],
       [ 0.01735238],
       [ 0.04721938],
       [-0.02467009],
       [-0.01438552],
       [ 0.01815932],
       [ 0.02761726],
       [-0.00256782],
       [-0.0430895 ],
       [ 0.04524681],
       [ 0.04253869],
       [ 0.01735238],
       [ 0.04721938],
       [-0.02467009],
       [-0.01438552],
       [ 0.01815932],
       [ 0.02761726],
       [-0.00256782],
       [-0.0430895 ],
       [ 0.04524681],
       [ 0.04253869],
       [ 0.01735238],
       [ 0.04721938],
       [-0.02467009],
       [-0.01438552],
       [ 0.01815932],
       [ 0.02761726],
       [-0.00256782],
       [-0.0430895 ],
       [ 0.04524681],
       [ 0.04253869],
       [ 0.01735238],
       [ 0.04721938],
       [-0.02467009],
       [-0.01438552],
       [-0.04576985],
       [ 0.00628718],
       [-0.04974582],
       [-0.04936311],
       [ 0.03441319],
       [ 0